CREATE TABLE regulatory_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(5000) NOT NULL,
    source VARCHAR(255) NOT NULL,
    jurisdiction VARCHAR(120) NOT NULL,
    category VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL,
    priority VARCHAR(40) NOT NULL,
    effective_date DATE,
    published_date DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE file_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_filename VARCHAR(300) NOT NULL,
    stored_filename VARCHAR(300) NOT NULL UNIQUE,
    content_type VARCHAR(150) NOT NULL,
    size_bytes BIGINT NOT NULL,
    storage_path VARCHAR(700) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);